version: "3"

services:
  firebase:
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/app/:delegated
    ports:
      - "5001:5001"
    container_name: firebase
